# Sticky Bits
PROT_INFO_PAGE_Msk = (0x400)
DISABLE_AUDIO_CODEC_ACC_Msk = (0x200)
DISABLE_QSPI_CONTROLLER_Msk = (0x100)
SECURE_BOOT_Msk = (0x80)
FORCE_CMAC_DEBUGGER_OFF_Msk = (0x40)
FORCE_M33_DEBUGGER_OFF_Msk = (0x20)
ENABLE_DCDC_Msk = (0x10)
PROT_USER_APP_CODE_Msk = (0x8)
PROT_VALID_KEY_Msk = (0x4)
PROT_APP_KEY_Msk = (0x2)
PROT_CONFIG_SCRIPT_Msk = (0x1)

sticky_bits_list = [
"PROT_INFO_PAGE",
"SECURE_BOOT",
"FORCE_CMAC_DEBUGGER_OFF",
"FORCE_M33_DEBUGGER_OFF",
"PROT_USER_APP_CODE",
"PROT_VALID_KEY",
"PROT_APP_KEY",
"PROT_CONFIG_SCRIPT"]